[package]
name = "state_cache"
version = "0.1.0"
authors = ["tiangong3624749 <tiangong3624749@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = { path = "../../libra/crypto/crypto" }
failure = { path = "../../libra/common/failure_ext", package = "failure_ext" }
types = { path = "../../libra/types" }
state_view = { path = "../../libra/storage/state_view" }
libradb = { path = "../../libra/storage/libradb" }
atomic_refcell = "0.1.3"
logger = { path = "../../libra/common/logger"}
star_types = { path = "../../star_types" }
state_store = { path = "../../storage/state_store" }
jellyfish_merkle = { path = "../../libra/storage/jellyfish_merkle" }
struct_cache = { path = "../../storage/struct_cache" }
scratchpad = { path = "../../libra/storage/scratchpad" }
