[workspace]

members = [
    "common/logger",
    "common/canonical_serialization",
    "common/failure_ext",
    "common/grpcio-client",
    "common/proptest_helpers",
    "common/proto_conv",
    "common/generic_sparse_merkle",
    "crypto/legacy_crypto",
    "crypto/nextgen_crypto",
    "storage/accumulator",
    "storage/sparse_merkle",
    "types",
    "star_types",
    "routing",
    "chain",
    "network",
    "sgwallet",
    "channel",
    "switch",
    "node",
]