[workspace]

members = [
    "common/logger",
    "common/canonical_serialization",
    "common/failure_ext",
    "common/grpcio-client",
    "common/proptest_helpers",
    "common/proto_conv",
    "common/channel",
    "config",
    "config/config_builder",
    "config/generate_keypair",
    "crypto/legacy_crypto",
    "crypto/nextgen_crypto",
    "storage/accumulator",
    "storage/state_view",
    "storage/scratchpad",
    "storage/state_storage",
    "storage/struct_cache",
    "storage/state_store",
    "language/vm",
    "language/vm/serializer_tests",
    "language/vm/vm_runtime",
    "language/vm/vm_runtime/vm_cache_map",
    "language/vm/vm_runtime/vm_runtime_types",
    "language/vm/vm_genesis",
    "language/bytecode_verifier",
    "language/bytecode_verifier/invalid_mutations",
    "language/bytecode_verifier/bytecode_verifier_tests",
    "language/compiler",
    "language/compiler/ir_to_bytecode",
    "language/compiler/ir_to_bytecode/syntax",
    "language/local_vm",
    "types",
    "star_types",
    "routing",
    "chain/chain_client",
    "chain/chain_service",
    "chain/mock_chain_client",
    "network",
    "network/memsocket",
    "network/netcore",
    "network-libp2p",
    "network-libp2p/peerset",
    "sgwallet",
    "sgwallet/local_state_storage",
    "switch",
    "node",
    "node/node_proto",
    "node/node_client",
    "node/node_service",
    "node/node_internal",
    "cli",
    "cli/cli_wallet",
]
