[workspace]

members = [
    "common/logger",
    "common/canonical_serialization",
    "common/failure_ext",
    "common/grpcio-client",
    "common/proptest_helpers",
    "common/proto_conv",
    "common/generic_sparse_merkle",
    "config",
    "config/config_builder",
    "config/generate_keypair",
    "crypto/legacy_crypto",
    "crypto/nextgen_crypto",
    "storage/accumulator",
    "storage/sparse_merkle",
    "storage/state_view",
    "storage/scratchpad",
    "storage/state_storage",
    "language/vm",
    "language/vm/serializer_tests",
    "language/vm/vm_runtime",
    "language/vm/vm_runtime/vm_cache_map",
    "language/vm/vm_runtime/vm_runtime_types",
    "language/vm/vm_genesis",
    "language/bytecode_verifier",
    "language/bytecode_verifier/invalid_mutations",
    "language/bytecode_verifier/bytecode_verifier_tests",
    "language/compiler",
    "language/compiler/ir_to_bytecode",
    "language/compiler/ir_to_bytecode/syntax",
    "types",
    "star_types",
    "routing",
    "chain",
    "network",
    "sgwallet",
    "switch",
    "node",
    "node/node_proto",
    "cli",
]