[workspace]

members = [
    "libra/common/logger",
    "libra/common/canonical_serialization",
    "libra/common/failure_ext",
    "libra/common/grpcio-client",
    "libra/common/proptest_helpers",
    "libra/common/proto_conv",
    "libra/common/channel",
    "libra/config",
    "libra/config/config_builder",
    "libra/config/generate_keypair",
    "libra/crypto/crypto",
    "libra/crypto/crypto_derive",
    "libra/storage/accumulator",
    "libra/storage/state_view",
    "libra/storage/scratchpad",
    "storage/state_storage",
    "storage/struct_cache",
    "storage/state_store",
    "libra/storage/jellyfish_merkle",
    "libra/language/vm",
    "libra/language/vm/serializer_tests",
    "libra/language/vm/vm_runtime",
    "libra/language/vm/vm_runtime/vm_cache_map",
    "libra/language/vm/vm_runtime/vm_runtime_types",
    "libra/language/vm/vm_genesis",
    "libra/language/bytecode_verifier",
    "libra/language/bytecode_verifier/invalid_mutations",
    "libra/language/bytecode_verifier/bytecode_verifier_tests",
    "libra/language/compiler",
    "libra/language/compiler/ir_to_bytecode",
    "libra/language/compiler/ir_to_bytecode/syntax",
    "language/local_vm",
    "libra/language/functional_tests",
    "libra/language/e2e_tests",
    "libra/language/transaction_builder",
    "libra/types",
    "star_types",
    "routing",
    "chain/chain_client",
    "chain/chain_service",
    "chain/mock_chain_client",
    "network",
    "network-libp2p",
    "network-libp2p/peerset",
    "sgwallet",
    "sgwallet/local_state_storage",
    "switch",
    "node",
    "node/node_proto",
    "node/node_client",
    "node/node_service",
    "node/node_internal",
    "cli",
    "cli/cli_wallet",
]

[replace]
"libp2p:0.7.0" = { git = "https://github.com/fikgol/rust-libp2p", tag = "v0.7.0-stargate" }
