version: '3'
services:
  wallet_node:
    build:
      context: .
      dockerfile: docker/node/node.Dockerfile
    ports:
    - "9000:9000"
    volumes:
      - ./logs/nodelogs:/logs
  gateway:
    build:
      context: .
      dockerfile: docker/grpcgateway/gateway.Dockerfile
    environment:
        GATEWAY_PORT: ":8081"
        NODE_PORT: ":9000"
    volumes:
        - ./logs/gatewaylogs:/gateway/log
    ports:
    - "8081:8081"
    depends_on:
      - wallet_node

