[package]
name = "state_store"
version = "0.1.0"
authors = ["jolestar <jolestar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = { path = "../../libra/common/failure_ext", package = "failure_ext" }
types = { path = "../../libra/types" }
star_types = { path = "../../star_types"}
state_view = { path = "../../libra/storage/state_view"}
crypto = { path = "../../libra/crypto/crypto" }
logger = { path = "../../libra/common/logger"}

[dev-dependencies]
types = { path = "../../libra/types", features = ["testing"]}