[package]
name = "memsocket"
version = "0.1.0"
authors = ["hit.cs.lijun@gmail.com"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = "0.4.12"
lazy_static = "1.3.0"
futures = { version = "=0.3.0-alpha.17", package = "futures-preview" }
