[package]
name = "cli"
version = "0.1.0"
authors = ["hit.cs.lijun@gmail.com"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = { version = "0.3.0-alpha.16", package = "futures-preview", features = ["async-await", "nightly", "io-compat", "compat"] }

bincode = "1.1.1"
grpcio = "0.4.3"
hex = "0.3.2"
hyper = "0.12.33"
itertools = "0.8.0"
proptest = "0.9.2"
rustyline = "4.1.0"
tokio = "0.1.22"
rust_decimal = "1.0.1"
num-traits = "0.2"
serde = { version = "1.0.96", features = ["derive"] }
serde_json = "1.0.40"
structopt = "0.2.15"
tempfile = "3.1.0"

config = { path = "../config" }
crypto = { path = "../crypto/legacy_crypto" }
nextgen_crypto = { path = "../crypto/nextgen_crypto" }
failure = { package = "failure_ext", path = "../common/failure_ext" }
libc = "0.2.60"
logger =  { path = "../common/logger" }
metrics = { path = "../common/metrics" }
proto_conv = { path = "../common/proto_conv" }
types = { path = "../types" }
vm_genesis = { path = "../language/vm/vm_genesis" }
node_client = { path = "../node/node_client"}
cli_wallet = { path = "./cli_wallet" }
chain_client = { path = "../chain/chain_client" }
node_proto = { path = "../node/node_proto" }
state_storage = { path = "../storage/state_storage" }

[dev-dependencies]
nextgen_crypto = { path = "../crypto/nextgen_crypto", features = ["testing"] }
types = { path = "../types" }