[package]
name = "node_proto"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.1.28"
grpcio = "0.4.4"
proptest = "0.9.2"
proptest-derive = "0.1.0"
protobuf = "2.7"
proto_conv = { path = "../../libra/common/proto_conv", features = ["derive"] }
grpc_helpers = { path = "../../libra/common/grpc_helpers" }
failure = { path = "../../libra/common/failure_ext", package = "failure_ext" }
proptest_helpers = { path = "../../libra/common/proptest_helpers" }
types = { package = "types", path = "../../libra/types"}

[build-dependencies]
build_helpers = { path = "../../libra/common/build_helpers" }

[dev-dependencies]
crypto = { path = "../../libra/crypto/crypto", features = ["testing"] }