[package]
name = "node_proto"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.1.28"
grpcio = "0.4.4"
proptest = "0.9.2"
proptest-derive = "0.1.0"
protobuf = "2.7"

[build-dependencies]
build_helpers = { path = "../../common/build_helpers" }