[package]
name = "network"
version = "0.1.0"
authors = ["hit.cs.lijun@gmail.com"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
libp2p = "0.11.0"
tokio = {version = "0.1.22"}
futures-preview = "0.2.2"
futures-channel-preview = "0.2.2"