[package]
name = "network"
version = "0.1.0"
authors = ["hit.cs.lijun@gmail.com"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
libp2p = "0.11.0"
tokio = {version = "0.1.22"}
futures = { version = "0.3.0-alpha.16", package = "futures-preview", features = ["async-await", "nightly", "io-compat", "compat"] }
memsocket = { path = "memsocket" }
netcore = { path = "netcore" }
sg_config = { path = "../sgconfig" }
nextgen_crypto = { path = "../crypto/nextgen_crypto", features = ["testing"] }
parity-multiaddr = "0.4.0"