[package]
name = "switch"
version = "0.1.0"
authors = ["fanngyuan@gmail.com"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
types = { package = "types", path = "../types" }
network = { package = "network", path = "../network"}