[package]
name = "local_state_storage"
version = "0.1.0"
authors = ["jolestar <jolestar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = { path = "../../common/failure_ext", package = "failure_ext" }
itertools = "0.8.0"
crypto = { path = "../../crypto/legacy_crypto" }
nextgen_crypto = { path = "../../crypto/nextgen_crypto" }
types = { path = "../../types"}
star_types = { path = "../../star_types" }
state_storage = {path = "../../storage/state_storage"}
chain_client = {path = "../../chain/chain_client"}
state_view = {path = "../../storage/state_view"}

[dev-dependencies]
nextgen_crypto = { path = "../../crypto/nextgen_crypto", features = ["testing"] }