[package]
name = "node"
version = "0.1.0"
authors = ["hit.cs.lijun@gmail.com"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
network = { package = "network", path = "../network"}
switch = { package = "switch",path="../switch"}