[package]
name = "channel-manager"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = { path = "../../libra/common/failure-ext", package = "libra-failure-ext"  }
itertools = "0.8.0"
libra-crypto = { path = "../../libra/crypto/crypto" }
libra-types = { path = "../../libra/types"}
sgtypes = { path = "../../sgtypes" }
sgchain = { path = "../../sgchain" }
libra-state-view = {path = "../../libra/storage/state-view"}
libra-logger = { path = "../../libra/common/logger"}
atomic_refcell = "0.1.3"
vm-runtime-types = { path = "../../libra/language/vm/vm-runtime/vm-runtime-types"}
tokio = "0.1.22"
sgstorage = { path = "../../sgstorage" }

lcs = { path = "../../libra/common/lcs", package = "libra-canonical-serialization"}
scratchpad = { path = "../../libra/storage/scratchpad" }
storage-proto = { path = "../../libra/storage/storage-proto" }
chashmap = "2.2"

[dev-dependencies]
libra-tools = { path = "../../libra/common/tools"}
sgconfig = { path = "../../sgconfig", package = "sg_config"}
rand = "0.6.5"