[package]
name = "star_types"
version = "0.1.0"
authors = ["jolestar <jolestar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.0-alpha.16", package = "futures-preview", features = ["async-await", "nightly", "io-compat", "compat"] }
types = { package = "types", path = "../types"}
proto_conv = { path = "../common/proto_conv", features = ["derive"] }
protobuf = "2.7"

[build-dependencies]
build_helpers = { path = "../common/build_helpers" }