[package]
name = "sgwallet"
version = "0.1.0"
authors = ["fanngyuan@gmail.com"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
rand = "0.6.5"
protobuf = "2.7"
atomic_refcell = "0.1.3"
failure = { path = "../common/failure_ext", package = "failure_ext" }
types = { path = "../types" }
star_types = { path = "../star_types" }
local_vm = { path = "../language/local_vm"}
crypto = { path = "../crypto/crypto" }
futures = { version = "0.3.0-alpha.16", package = "futures-preview", features = ["async-await", "nightly", "io-compat", "compat"] }
local_state_storage = { path = "./local_state_storage"}
chain_client = { path = "../chain/chain_client"}
vm_genesis = { path = "../language/vm/vm_genesis" }
logger = { path = "../common/logger"}
state_store = { path = "../storage/state_store"}
tokio = "0.1.22"
futures_01 = { package = "futures", version = "0.1.28" }


[dev-dependencies]
crypto = { path = "../crypto/crypto", features = ["testing"] }
mock_chain_client = { path = "../chain/mock_chain_client" }